version: "3.5"
services:

    redis:
      image: redis:alpine
      container_name: php-redis

    mysql:
      image: mysql:8.0
      container_name: php-mysql
      volumes:
        - "./database:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: php-webserver
      volumes:
          - ../infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: php-fpm
      container_name: php-fpm
      volumes:
        - ${SYMFONY_APP_PATH}:/application
        - ../infrastructure/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ./var:/application/var

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8081:80"